# -*- coding: utf-8 -*-
"""Python_Variables_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqFecPqadjsuiak9eSGUydSUg3qU9IYa

# Python Variables Practice (Assignment 1)

**Topics Covered:**
- Variable creation
- int, float, str, bool data types
- Printing variables
- f-strings

## Section 1: Variable Creation & Printing

### Question 1
Create a variable to store your **age** and print it.
"""

# write your answer

age =35

print(age)

"""### Question 2
Create a variable to store the **price of a notebook** (can be a decimal value) and print it.
"""

# write your answer
price = 75.0
print(price)

"""### Question 3
Create a variable to store your **first name** and print it.
"""

# write your answer
first_name = "shivam"
print(first_name)

"""### Question 4
Create a variable to store whether you have **completed today’s class** (True/False) and print it.
"""

# write your answer
completed = True
print(completed)

"""### Question 5
Create two variables:
- one to store the **number of classes attended**
- one to store the **average rating** (float)
Print both.
"""

# write your answer
classes = 26
rating = 5.7
print(classes)
print(rating)

"""## Section 2: Printing using f-strings

### Question 6
Create variables for **name** and **age** and print:
> My name is Rahul and I am 22 years old.
"""

# write your answer
name = "shivam"
age = 21
print(f"My name is {name} and i am {age} years old")

"""
### Question 7
Create variables for **item name** and **price** and print:
> The price of Pen is 10.5 rupees."""

# write your answer
item_name = "pen"
price = 7.6
print(f"the price of {item_name} is {price} rupees")

"""### Question 8
Create variables for **batch name** and **class completed status** and print:
> Batch DA10 class completed status is True.
"""

# write your answer
bach_name = "DA10"
class_competed_status = "True"
print(f"Batch {bach_name} class completed status is {class_competed_status}")

